// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FKPI_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190629215611_set children virtual 2")]
    partial class setchildrenvirtual2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FKPI_API.Models.Account", b =>
                {
                    b.Property<int>("AccountId");

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.Property<int?>("ParentAccountId");

                    b.HasKey("AccountId");

                    b.HasIndex("ParentAccountId");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("FKPI_API.Models.AccountValue", b =>
                {
                    b.Property<int>("AccountValueId");

                    b.Property<int>("AccountId");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Year");

                    b.HasKey("AccountValueId");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountValue");
                });

            modelBuilder.Entity("FKPI_API.Models.KPI", b =>
                {
                    b.Property<int>("KPIId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Formula");

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.HasKey("KPIId");

                    b.ToTable("KPI");
                });

            modelBuilder.Entity("FKPI_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("FKPI_API.Models.Account", b =>
                {
                    b.HasOne("FKPI_API.Models.Account", "ParentAccount")
                        .WithMany("Children")
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FKPI_API.Models.AccountValue", b =>
                {
                    b.HasOne("FKPI_API.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
